package com.lkjc.consumablesmanager.mapper;

import com.lkjc.consumablesmanager.entity.ConsumableSpecification;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConsumableSpecificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumable_specification
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("id") Integer id, @Param("consumableItemId") Integer consumableItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumable_specification
     *
     * @mbg.generated
     */
    int insert(ConsumableSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumable_specification
     *
     * @mbg.generated
     */
    ConsumableSpecification selectByPrimaryKey(@Param("id") Integer id, @Param("consumableItemId") Integer consumableItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumable_specification
     *
     * @mbg.generated
     */
    List<ConsumableSpecification> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumable_specification
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ConsumableSpecification record);

    List<ConsumableSpecification> select(ConsumableSpecification consumableSpecification);
}