package com.lkjc.consumablesmanager.mapper;

import com.lkjc.consumablesmanager.entity.ConsumableType;
import java.util.List;

public interface ConsumableTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumable_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumable_type
     *
     * @mbg.generated
     */
    int insert(ConsumableType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumable_type
     *
     * @mbg.generated
     */
    ConsumableType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumable_type
     *
     * @mbg.generated
     */
    List<ConsumableType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumable_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ConsumableType record);

    List<ConsumableType> select(ConsumableType consumableType);
}