package com.lkjc.consumablesmanager.mapper;

import com.lkjc.consumablesmanager.entity.ConsumableItem;
import com.lkjc.consumablesmanager.entity.PageInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ConsumableItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumable_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumable_item
     *
     * @mbg.generated
     */
    int insert(ConsumableItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumable_item
     *
     * @mbg.generated
     */
    ConsumableItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumable_item
     *
     * @mbg.generated
     */
    List<ConsumableItem> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumable_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ConsumableItem record);

    int selectCount(ConsumableItem record);

    List<ConsumableItem> select(ConsumableItem consumableItem);
    List<ConsumableItem> selectPage(@Param("pageInfo") PageInfo pageInfo, @Param("consumableItem") ConsumableItem consumableItem);
}