package com.lkjc.consumablesmanager.mapper;

import com.lkjc.consumablesmanager.entity.ConsumablePurchaseRecord;
import com.lkjc.consumablesmanager.entity.ConsumableStatiticsInit;
import com.lkjc.consumablesmanager.entity.PageInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ConsumablePurchaseRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumable_purchase_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumable_purchase_record
     *
     * @mbg.generated
     */
    int insert(ConsumablePurchaseRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumable_purchase_record
     *
     * @mbg.generated
     */
    ConsumablePurchaseRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumable_purchase_record
     *
     * @mbg.generated
     */
    List<ConsumablePurchaseRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumable_purchase_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ConsumablePurchaseRecord record);

    List<ConsumablePurchaseRecord> conductStatistics(ConsumableStatiticsInit consumableStatiticsInit);

    List<ConsumablePurchaseRecord> selectPage(@Param("pageInfo") PageInfo pageInfo, @Param("consumablePurchaseRecord") ConsumablePurchaseRecord record);

    int selectCount(@Param("consumablePurchaseRecord") ConsumablePurchaseRecord record);



}