package com.lkjc.consumablesmanager.mapper;

import com.lkjc.consumablesmanager.entity.RoleAuthorityRel;

import java.util.List;

public interface RoleAuthorityRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority_rel
     *
     * @mbg.generated
     */
    int insert(RoleAuthorityRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_authority_rel
     *
     * @mbg.generated
     */
    List<RoleAuthorityRel> selectAll();


    List<RoleAuthorityRel> select(RoleAuthorityRel roleAuthorityRel);


    List<RoleAuthorityRel> getAuthorityByRole(RoleAuthorityRel roleAuthorityRel);

}