package com.lkjc.consumablesmanager.mapper;

import com.lkjc.consumablesmanager.entity.UnitItem;
import java.util.List;

public interface UnitItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_item
     *
     * @mbg.generated
     */
    int insert(UnitItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_item
     *
     * @mbg.generated
     */
    UnitItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_item
     *
     * @mbg.generated
     */
    List<UnitItem> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UnitItem record);
}