package com.lkjc.consumablesmanager.mapper;

import com.lkjc.consumablesmanager.entity.UserRoleRel;

import java.util.List;

public interface UserRoleRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_rel
     *
     * @mbg.generated
     */
    int insert(UserRoleRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role_rel
     *
     * @mbg.generated
     */
    List<UserRoleRel> selectAll();



    List<UserRoleRel> select(UserRoleRel userRoleRel);
}