package com.lkjc.consumablesmanager.entity;

import java.util.Date;

public class Authority {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.authority_id
     *
     * @mbg.generated
     */
    private String authorityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.resource
     *
     * @mbg.generated
     */
    private String resource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.operation
     *
     * @mbg.generated
     */
    private String operation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.sts
     *
     * @mbg.generated
     */
    private String sts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.desc
     *
     * @mbg.generated
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.sts_date
     *
     * @mbg.generated
     */
    private Date stsDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.authority_id
     *
     * @return the value of authority.authority_id
     *
     * @mbg.generated
     */
    public String getAuthorityId() {
        return authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.authority_id
     *
     * @param authorityId the value for authority.authority_id
     *
     * @mbg.generated
     */
    public void setAuthorityId(String authorityId) {
        this.authorityId = authorityId == null ? null : authorityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.resource
     *
     * @return the value of authority.resource
     *
     * @mbg.generated
     */
    public String getResource() {
        return resource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.resource
     *
     * @param resource the value for authority.resource
     *
     * @mbg.generated
     */
    public void setResource(String resource) {
        this.resource = resource == null ? null : resource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.operation
     *
     * @return the value of authority.operation
     *
     * @mbg.generated
     */
    public String getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.operation
     *
     * @param operation the value for authority.operation
     *
     * @mbg.generated
     */
    public void setOperation(String operation) {
        this.operation = operation == null ? null : operation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.sts
     *
     * @return the value of authority.sts
     *
     * @mbg.generated
     */
    public String getSts() {
        return sts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.sts
     *
     * @param sts the value for authority.sts
     *
     * @mbg.generated
     */
    public void setSts(String sts) {
        this.sts = sts == null ? null : sts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.desc
     *
     * @return the value of authority.desc
     *
     * @mbg.generated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.desc
     *
     * @param desc the value for authority.desc
     *
     * @mbg.generated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.create_date
     *
     * @return the value of authority.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.create_date
     *
     * @param createDate the value for authority.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.sts_date
     *
     * @return the value of authority.sts_date
     *
     * @mbg.generated
     */
    public Date getStsDate() {
        return stsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.sts_date
     *
     * @param stsDate the value for authority.sts_date
     *
     * @mbg.generated
     */
    public void setStsDate(Date stsDate) {
        this.stsDate = stsDate;
    }
}