package com.lkjc.consumablesmanager.entity;

import java.sql.Timestamp;
import java.util.Date;

public class ConsumableConsumptionRecord extends Entity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumable_consumption_record.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumable_consumption_record.consumable_item_id
     *
     * @mbg.generated
     */
    private Integer consumableItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumable_consumption_record.consumable_specification_id
     *
     * @mbg.generated
     */
    private Integer consumableSpecificationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumable_consumption_record.consumable_type_id
     *
     * @mbg.generated
     */
    private Integer consumableTypeId;


    private String consumableItemName;

    private String consumableSpecificationName;

    private String consumableTypeName;

    public String getConsumableItemName() {
        return consumableItemName;
    }

    public void setConsumableItemName(String consumableItemName) {
        this.consumableItemName = consumableItemName;
    }

    public String getConsumableSpecificationName() {
        return consumableSpecificationName;
    }

    public void setConsumableSpecificationName(String consumableSpecificationName) {
        this.consumableSpecificationName = consumableSpecificationName;
    }

    public String getConsumableTypeName() {
        return consumableTypeName;
    }

    public void setConsumableTypeName(String consumableTypeName) {
        this.consumableTypeName = consumableTypeName;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumable_consumption_record.recipients_id
     *
     * @mbg.generated
     */
    private Integer recipientsId;
    private String recipientsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumable_consumption_record.reviewer_id
     *
     * @mbg.generated
     */
    private Integer reviewerId;
    private String reviewerName;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumable_consumption_record.count
     *
     * @mbg.generated
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumable_consumption_record.unit_id
     *
     * @mbg.generated
     */
    private Integer unitId;
    private String unitName;

    public String getRecipientsName() {
        return recipientsName;
    }

    public void setRecipientsName(String recipientsName) {
        this.recipientsName = recipientsName;
    }

    public String getReviewerName() {
        return reviewerName;
    }

    public void setReviewerName(String reviewerName) {
        this.reviewerName = reviewerName;
    }

    public String getUnitName() {
        return unitName;
    }

    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }

    private Timestamp timeBegin;
    private Timestamp timeEnd;

    public Timestamp getTimeBegin() {
        return timeBegin;
    }

    public void setTimeBegin(Timestamp timeBegin) {
        this.timeBegin = timeBegin;
    }

    public Timestamp getTimeEnd() {
        return timeEnd;
    }

    public void setTimeEnd(Timestamp timeEnd) {
        this.timeEnd = timeEnd;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumable_consumption_record.sts
     *
     * @mbg.generated
     */
    private String sts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumable_consumption_record.sts_date
     *
     * @mbg.generated
     */
    private Date stsDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumable_consumption_record.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumable_consumption_record.id
     *
     * @return the value of consumable_consumption_record.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumable_consumption_record.id
     *
     * @param id the value for consumable_consumption_record.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumable_consumption_record.consumable_item_id
     *
     * @return the value of consumable_consumption_record.consumable_item_id
     *
     * @mbg.generated
     */
    public Integer getConsumableItemId() {
        return consumableItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumable_consumption_record.consumable_item_id
     *
     * @param consumableItemId the value for consumable_consumption_record.consumable_item_id
     *
     * @mbg.generated
     */
    public void setConsumableItemId(Integer consumableItemId) {
        this.consumableItemId = consumableItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumable_consumption_record.consumable_specification_id
     *
     * @return the value of consumable_consumption_record.consumable_specification_id
     *
     * @mbg.generated
     */
    public Integer getConsumableSpecificationId() {
        return consumableSpecificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumable_consumption_record.consumable_specification_id
     *
     * @param consumableSpecificationId the value for consumable_consumption_record.consumable_specification_id
     *
     * @mbg.generated
     */
    public void setConsumableSpecificationId(Integer consumableSpecificationId) {
        this.consumableSpecificationId = consumableSpecificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumable_consumption_record.consumable_type_id
     *
     * @return the value of consumable_consumption_record.consumable_type_id
     *
     * @mbg.generated
     */
    public Integer getConsumableTypeId() {
        return consumableTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumable_consumption_record.consumable_type_id
     *
     * @param consumableTypeId the value for consumable_consumption_record.consumable_type_id
     *
     * @mbg.generated
     */
    public void setConsumableTypeId(Integer consumableTypeId) {
        this.consumableTypeId = consumableTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumable_consumption_record.recipients_id
     *
     * @return the value of consumable_consumption_record.recipients_id
     *
     * @mbg.generated
     */
    public Integer getRecipientsId() {
        return recipientsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumable_consumption_record.recipients_id
     *
     * @param recipientsId the value for consumable_consumption_record.recipients_id
     *
     * @mbg.generated
     */
    public void setRecipientsId(Integer recipientsId) {
        this.recipientsId = recipientsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumable_consumption_record.reviewer_id
     *
     * @return the value of consumable_consumption_record.reviewer_id
     *
     * @mbg.generated
     */
    public Integer getReviewerId() {
        return reviewerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumable_consumption_record.reviewer_id
     *
     * @param reviewerId the value for consumable_consumption_record.reviewer_id
     *
     * @mbg.generated
     */
    public void setReviewerId(Integer reviewerId) {
        this.reviewerId = reviewerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumable_consumption_record.count
     *
     * @return the value of consumable_consumption_record.count
     *
     * @mbg.generated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumable_consumption_record.count
     *
     * @param count the value for consumable_consumption_record.count
     *
     * @mbg.generated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumable_consumption_record.unit_id
     *
     * @return the value of consumable_consumption_record.unit_id
     *
     * @mbg.generated
     */
    public Integer getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumable_consumption_record.unit_id
     *
     * @param unitId the value for consumable_consumption_record.unit_id
     *
     * @mbg.generated
     */
    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumable_consumption_record.sts
     *
     * @return the value of consumable_consumption_record.sts
     *
     * @mbg.generated
     */
    public String getSts() {
        return sts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumable_consumption_record.sts
     *
     * @param sts the value for consumable_consumption_record.sts
     *
     * @mbg.generated
     */
    public void setSts(String sts) {
        this.sts = sts == null ? null : sts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumable_consumption_record.sts_date
     *
     * @return the value of consumable_consumption_record.sts_date
     *
     * @mbg.generated
     */
    public Date getStsDate() {
        return stsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumable_consumption_record.sts_date
     *
     * @param stsDate the value for consumable_consumption_record.sts_date
     *
     * @mbg.generated
     */
    public void setStsDate(Date stsDate) {
        this.stsDate = stsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumable_consumption_record.create_date
     *
     * @return the value of consumable_consumption_record.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumable_consumption_record.create_date
     *
     * @param createDate the value for consumable_consumption_record.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}