package com.lkjc.consumablesmanager.entity;

import java.sql.Timestamp;
import java.util.Date;

public class ConsumablePurchaseRecord extends Entity{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumable_purchase_record.id
     *
     * @mbg.generated
     */
    private Integer id;

    private Timestamp timeBegin;
    private Timestamp timeEnd;

    public Timestamp getTimeBegin() {
        return timeBegin;
    }

    public void setTimeBegin(Timestamp timeBegin) {
        this.timeBegin = timeBegin;
    }

    public Timestamp getTimeEnd() {
        return timeEnd;
    }

    public void setTimeEnd(Timestamp timeEnd) {
        this.timeEnd = timeEnd;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumable_purchase_record.consumable_item_id
     *
     * @mbg.generated
     */
    private Integer consumableItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumable_purchase_record.consumable_specification_id
     *
     * @mbg.generated
     */
    private Integer consumableSpecificationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumable_purchase_record.consumable_type_id
     *
     * @mbg.generated
     */
    private Integer consumableTypeId;
    private String consumableItemName;

    private String consumableSpecificationName;

    private String consumableTypeName;

    public String getConsumableItemName() {
        return consumableItemName;
    }

    public void setConsumableItemName(String consumableItemName) {
        this.consumableItemName = consumableItemName;
    }

    public String getConsumableSpecificationName() {
        return consumableSpecificationName;
    }

    public void setConsumableSpecificationName(String consumableSpecificationName) {
        this.consumableSpecificationName = consumableSpecificationName;
    }

    public String getConsumableTypeName() {
        return consumableTypeName;
    }

    public void setConsumableTypeName(String consumableTypeName) {
        this.consumableTypeName = consumableTypeName;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumable_purchase_record.unit_price
     *
     * @mbg.generated
     */
    private Double unitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumable_purchase_record.total_price
     *
     * @mbg.generated
     */
    private Double totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumable_purchase_record.buyer_id
     *
     * @mbg.generated
     */
    private Integer buyerId;
    private String buyerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumable_purchase_record.reviewer_id
     *
     * @mbg.generated
     */
    private Integer reviewerId;
    private String reviewerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumable_purchase_record.unit_id
     *
     * @mbg.generated
     */
    private Integer unitId;
    private String unitName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumable_purchase_record.count
     *
     * @mbg.generated
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumable_purchase_record.sts
     *
     * @mbg.generated
     */
    private String sts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumable_purchase_record.sts_date
     *
     * @mbg.generated
     */
    private Date stsDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumable_purchase_record.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    private String createDateFormat;

    public String getCreateDateFormat() {
        return createDateFormat;
    }

    public void setCreateDateFormat(String createDateFormat) {
        this.createDateFormat = createDateFormat;
    }

    public String getBuyerName() {
        return buyerName;
    }

    public void setBuyerName(String buyerName) {
        this.buyerName = buyerName;
    }

    public String getReviewerName() {
        return reviewerName;
    }

    public void setReviewerName(String reviewerName) {
        this.reviewerName = reviewerName;
    }

    public String getUnitName() {
        return unitName;
    }

    public void setUnitName(String unitName) {
        this.unitName = unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumable_purchase_record.id
     *
     * @return the value of consumable_purchase_record.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumable_purchase_record.id
     *
     * @param id the value for consumable_purchase_record.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumable_purchase_record.consumable_item_id
     *
     * @return the value of consumable_purchase_record.consumable_item_id
     *
     * @mbg.generated
     */
    public Integer getConsumableItemId() {
        return consumableItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumable_purchase_record.consumable_item_id
     *
     * @param consumableItemId the value for consumable_purchase_record.consumable_item_id
     *
     * @mbg.generated
     */
    public void setConsumableItemId(Integer consumableItemId) {
        this.consumableItemId = consumableItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumable_purchase_record.consumable_specification_id
     *
     * @return the value of consumable_purchase_record.consumable_specification_id
     *
     * @mbg.generated
     */
    public Integer getConsumableSpecificationId() {
        return consumableSpecificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumable_purchase_record.consumable_specification_id
     *
     * @param consumableSpecificationId the value for consumable_purchase_record.consumable_specification_id
     *
     * @mbg.generated
     */
    public void setConsumableSpecificationId(Integer consumableSpecificationId) {
        this.consumableSpecificationId = consumableSpecificationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumable_purchase_record.consumable_type_id
     *
     * @return the value of consumable_purchase_record.consumable_type_id
     *
     * @mbg.generated
     */
    public Integer getConsumableTypeId() {
        return consumableTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumable_purchase_record.consumable_type_id
     *
     * @param consumableTypeId the value for consumable_purchase_record.consumable_type_id
     *
     * @mbg.generated
     */
    public void setConsumableTypeId(Integer consumableTypeId) {
        this.consumableTypeId = consumableTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumable_purchase_record.unit_price
     *
     * @return the value of consumable_purchase_record.unit_price
     *
     * @mbg.generated
     */
    public Double getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumable_purchase_record.unit_price
     *
     * @param unitPrice the value for consumable_purchase_record.unit_price
     *
     * @mbg.generated
     */
    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumable_purchase_record.total_price
     *
     * @return the value of consumable_purchase_record.total_price
     *
     * @mbg.generated
     */
    public Double getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumable_purchase_record.total_price
     *
     * @param totalPrice the value for consumable_purchase_record.total_price
     *
     * @mbg.generated
     */
    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumable_purchase_record.buyer_id
     *
     * @return the value of consumable_purchase_record.buyer_id
     *
     * @mbg.generated
     */
    public Integer getBuyerId() {
        return buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumable_purchase_record.buyer_id
     *
     * @param buyerId the value for consumable_purchase_record.buyer_id
     *
     * @mbg.generated
     */
    public void setBuyerId(Integer buyerId) {
        this.buyerId = buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumable_purchase_record.reviewer_id
     *
     * @return the value of consumable_purchase_record.reviewer_id
     *
     * @mbg.generated
     */
    public Integer getReviewerId() {
        return reviewerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumable_purchase_record.reviewer_id
     *
     * @param reviewerId the value for consumable_purchase_record.reviewer_id
     *
     * @mbg.generated
     */
    public void setReviewerId(Integer reviewerId) {
        this.reviewerId = reviewerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumable_purchase_record.unit_id
     *
     * @return the value of consumable_purchase_record.unit_id
     *
     * @mbg.generated
     */
    public Integer getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumable_purchase_record.unit_id
     *
     * @param unitId the value for consumable_purchase_record.unit_id
     *
     * @mbg.generated
     */
    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumable_purchase_record.count
     *
     * @return the value of consumable_purchase_record.count
     *
     * @mbg.generated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumable_purchase_record.count
     *
     * @param count the value for consumable_purchase_record.count
     *
     * @mbg.generated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumable_purchase_record.sts
     *
     * @return the value of consumable_purchase_record.sts
     *
     * @mbg.generated
     */
    public String getSts() {
        return sts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumable_purchase_record.sts
     *
     * @param sts the value for consumable_purchase_record.sts
     *
     * @mbg.generated
     */
    public void setSts(String sts) {
        this.sts = sts == null ? null : sts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumable_purchase_record.sts_date
     *
     * @return the value of consumable_purchase_record.sts_date
     *
     * @mbg.generated
     */
    public Date getStsDate() {
        return stsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumable_purchase_record.sts_date
     *
     * @param stsDate the value for consumable_purchase_record.sts_date
     *
     * @mbg.generated
     */
    public void setStsDate(Date stsDate) {
        this.stsDate = stsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumable_purchase_record.create_date
     *
     * @return the value of consumable_purchase_record.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumable_purchase_record.create_date
     *
     * @param createDate the value for consumable_purchase_record.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}