package com.lkjc.consumablesmanager.entity;

import java.util.Date;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_id
     *
     * @mbg.generated
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.sts
     *
     * @mbg.generated
     */
    private String sts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.sts_date
     *
     * @mbg.generated
     */
    private Date stsDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_name
     *
     * @mbg.generated
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_desc
     *
     * @mbg.generated
     */
    private String roleDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_id
     *
     * @return the value of role.role_id
     *
     * @mbg.generated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_id
     *
     * @param roleId the value for role.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.sts
     *
     * @return the value of role.sts
     *
     * @mbg.generated
     */
    public String getSts() {
        return sts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.sts
     *
     * @param sts the value for role.sts
     *
     * @mbg.generated
     */
    public void setSts(String sts) {
        this.sts = sts == null ? null : sts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.sts_date
     *
     * @return the value of role.sts_date
     *
     * @mbg.generated
     */
    public Date getStsDate() {
        return stsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.sts_date
     *
     * @param stsDate the value for role.sts_date
     *
     * @mbg.generated
     */
    public void setStsDate(Date stsDate) {
        this.stsDate = stsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.create_date
     *
     * @return the value of role.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.create_date
     *
     * @param createDate the value for role.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_name
     *
     * @return the value of role.role_name
     *
     * @mbg.generated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_name
     *
     * @param roleName the value for role.role_name
     *
     * @mbg.generated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_desc
     *
     * @return the value of role.role_desc
     *
     * @mbg.generated
     */
    public String getRoleDesc() {
        return roleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_desc
     *
     * @param roleDesc the value for role.role_desc
     *
     * @mbg.generated
     */
    public void setRoleDesc(String roleDesc) {
        this.roleDesc = roleDesc == null ? null : roleDesc.trim();
    }
}