package com.lkjc.consumablesmanager.entity;

import java.util.Date;

public class RoleAuthorityRel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_authority_rel.role_id
     *
     * @mbg.generated
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_authority_rel.authority_id
     *
     * @mbg.generated
     */
    private String authorityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_authority_rel.sts
     *
     * @mbg.generated
     */
    private String sts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_authority_rel.sts_date
     *
     * @mbg.generated
     */
    private Date stsDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_authority_rel.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_authority_rel.role_id
     *
     * @return the value of role_authority_rel.role_id
     *
     * @mbg.generated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_authority_rel.role_id
     *
     * @param roleId the value for role_authority_rel.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_authority_rel.authority_id
     *
     * @return the value of role_authority_rel.authority_id
     *
     * @mbg.generated
     */
    public String getAuthorityId() {
        return authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_authority_rel.authority_id
     *
     * @param authorityId the value for role_authority_rel.authority_id
     *
     * @mbg.generated
     */
    public void setAuthorityId(String authorityId) {
        this.authorityId = authorityId == null ? null : authorityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_authority_rel.sts
     *
     * @return the value of role_authority_rel.sts
     *
     * @mbg.generated
     */
    public String getSts() {
        return sts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_authority_rel.sts
     *
     * @param sts the value for role_authority_rel.sts
     *
     * @mbg.generated
     */
    public void setSts(String sts) {
        this.sts = sts == null ? null : sts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_authority_rel.sts_date
     *
     * @return the value of role_authority_rel.sts_date
     *
     * @mbg.generated
     */
    public Date getStsDate() {
        return stsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_authority_rel.sts_date
     *
     * @param stsDate the value for role_authority_rel.sts_date
     *
     * @mbg.generated
     */
    public void setStsDate(Date stsDate) {
        this.stsDate = stsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_authority_rel.create_date
     *
     * @return the value of role_authority_rel.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_authority_rel.create_date
     *
     * @param createDate the value for role_authority_rel.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}