package com.lkjc.consumablesmanager.entity;

public class SysConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.SYS_CONFIG_ID
     *
     * @mbg.generated
     */
    private String sysConfigId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.CUR_VALUE
     *
     * @mbg.generated
     */
    private String curValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.VALUE_DESC
     *
     * @mbg.generated
     */
    private String valueDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.SYS_CONFIG_ID
     *
     * @return the value of sys_config.SYS_CONFIG_ID
     *
     * @mbg.generated
     */
    public String getSysConfigId() {
        return sysConfigId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.SYS_CONFIG_ID
     *
     * @param sysConfigId the value for sys_config.SYS_CONFIG_ID
     *
     * @mbg.generated
     */
    public void setSysConfigId(String sysConfigId) {
        this.sysConfigId = sysConfigId == null ? null : sysConfigId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.NAME
     *
     * @return the value of sys_config.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.NAME
     *
     * @param name the value for sys_config.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.CUR_VALUE
     *
     * @return the value of sys_config.CUR_VALUE
     *
     * @mbg.generated
     */
    public String getCurValue() {
        return curValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.CUR_VALUE
     *
     * @param curValue the value for sys_config.CUR_VALUE
     *
     * @mbg.generated
     */
    public void setCurValue(String curValue) {
        this.curValue = curValue == null ? null : curValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.VALUE_DESC
     *
     * @return the value of sys_config.VALUE_DESC
     *
     * @mbg.generated
     */
    public String getValueDesc() {
        return valueDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.VALUE_DESC
     *
     * @param valueDesc the value for sys_config.VALUE_DESC
     *
     * @mbg.generated
     */
    public void setValueDesc(String valueDesc) {
        this.valueDesc = valueDesc == null ? null : valueDesc.trim();
    }
}