package com.lkjc.consumablesmanager.entity;

import java.util.Date;

public class UserRoleRel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_rel.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_rel.role_id
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_rel.sts
     *
     * @mbg.generated
     */
    private String sts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_rel.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_rel.sts_date
     *
     * @mbg.generated
     */
    private Date stsDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_rel.user_id
     *
     * @return the value of user_role_rel.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_rel.user_id
     *
     * @param userId the value for user_role_rel.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_rel.role_id
     *
     * @return the value of user_role_rel.role_id
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_rel.role_id
     *
     * @param roleId the value for user_role_rel.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_rel.sts
     *
     * @return the value of user_role_rel.sts
     *
     * @mbg.generated
     */
    public String getSts() {
        return sts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_rel.sts
     *
     * @param sts the value for user_role_rel.sts
     *
     * @mbg.generated
     */
    public void setSts(String sts) {
        this.sts = sts == null ? null : sts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_rel.create_date
     *
     * @return the value of user_role_rel.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_rel.create_date
     *
     * @param createDate the value for user_role_rel.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_rel.sts_date
     *
     * @return the value of user_role_rel.sts_date
     *
     * @mbg.generated
     */
    public Date getStsDate() {
        return stsDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_rel.sts_date
     *
     * @param stsDate the value for user_role_rel.sts_date
     *
     * @mbg.generated
     */
    public void setStsDate(Date stsDate) {
        this.stsDate = stsDate;
    }
}